In [1]:
import transformers
import torch
from src import Tokenizer

In [2]:
tokenizer = Tokenizer('gpt2')
gpt_model = transformers.GPT2LMHeadModel.from_pretrained('gpt2')

tensor([11484, 12456,   290, 41123,  4528,  6190,   319,   262, 46448,    11,
         8620,   511,  3777,   351,   257, 45736,  1175,  3960,    13])

In [7]:
from src import linear_unidirectional_graph_maker

sample_text = "Legolas and Gimli advanced on the orcs, raising their weapons with a harrowing war cry."
x=tokenizer(sample_text)

graph_maker=linear_unidirectional_graph_maker(5)
edge_index=graph_maker(len(x))
x,edge_index

(tensor([11484, 12456,   290, 41123,  4528,  6190,   319,   262, 46448,    11,
          8620,   511,  3777,   351,   257, 45736,  1175,  3960,    13]),
 tensor([[ 0,  0,  1,  0,  1,  2,  0,  1,  2,  3,  0,  1,  2,  3,  4,  0,  1,  2,
           3,  4,  5,  1,  2,  3,  4,  5,  6,  2,  3,  4,  5,  6,  7,  3,  4,  5,
           6,  7,  8,  4,  5,  6,  7,  8,  9,  5,  6,  7,  8,  9, 10,  6,  7,  8,
           9, 10, 11,  7,  8,  9, 10, 11, 12,  8,  9, 10, 11, 12, 13,  9, 10, 11,
          12, 13, 14, 10, 11, 12, 13, 14, 15, 11, 12, 13, 14, 15, 16, 12, 13, 14,
          15, 16, 17, 13, 14, 15, 16, 17, 18],
         [ 0,  1,  1,  2,  2,  2,  3,  3,  3,  3,  4,  4,  4,  4,  4,  5,  5,  5,
           5,  5,  5,  6,  6,  6,  6,  6,  6,  7,  7,  7,  7,  7,  7,  8,  8,  8,
           8,  8,  8,  9,  9,  9,  9,  9,  9, 10, 10, 10, 10, 10, 10, 11, 11, 11,
          11, 11, 11, 12, 12, 12, 12, 12, 12, 13, 13, 13, 13, 13, 13, 14, 14, 14,
          14, 14, 14, 15, 15, 15, 15, 15, 15, 16, 16, 16, 16, 

In [8]:
from src.GPT2 import GPT2, GPT2_Encoder, GPT2_LM_Head

encoder=GPT2_Encoder()
decoder=GPT2_LM_Head()

model=GPT2(encoder, decoder, tokenizer)

model.load_from_original(gpt_model)

In [9]:
model(x,edge_index)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (19x768 and 3072x768)

torch.Size([1, 10])

In [3]:
import torch
def count_parameters(model):
    """Count the number of parameters in a model."""
    return sum([p.numel() for p in model.parameters()])

conv = torch.nn.Conv1d(8,32,1)
print(count_parameters(conv))
# 288

linear = torch.nn.Linear(8,32)
print(count_parameters(linear))
# 288

print(conv.weight.shape)
print(conv.bias.shape)
# torch.Size([32, 8, 1])
print(linear.weight.shape)
print(linear.bias.shape)
# torch.Size([32, 8])

# use same initialization
linear.weight = torch.nn.Parameter(conv.weight.squeeze(2))
linear.bias = torch.nn.Parameter(conv.bias)

288
288
torch.Size([32, 8, 1])
torch.Size([32])
torch.Size([32, 8])
torch.Size([32])
